services:
  postgres:
    image: postgres:16
    container_name: postgres-market-price
    ports:
      - 5433:5432
    volumes:
      - postgres-db-market-price:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - pipeline-network
    healthcheck:
      test: ["CMD", "pg_isready","-d","${POSTGRES_DB}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 30s

volumes:
  postgres-db-market-price:

networks:
  pipeline-network:
    external: true